// 从 opencc-js 的字典文件(jsdelivr 下载)生成 Dart 常量表。
// 输入: STCharacters.js / STPhrases.js / TSCharacters.js / TSPhrases.js
// 输出: lib/core/l10n/han_data.dart
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const outPath = path.resolve(here, '../../lib/core/l10n/han_data.dart')

function parseJs(file) {
  const raw = fs.readFileSync(path.join(here, file), 'utf8')
  // export default "a b|c d|..."
  const m = raw.match(/export default\s+"([\s\S]*)"\s*;?/)
  if (!m) throw new Error(`cannot parse ${file}`)
  const body = m[1]
  const pairs = new Map()
  let maxLen = 1
  for (const entry of body.split('|')) {
    if (!entry.trim()) continue
    const idx = entry.indexOf(' ')
    if (idx <= 0) continue
    const from = entry.slice(0, idx).trim()
    const to = entry.slice(idx + 1).trim()
    if (!from || !to) continue
    // 一个简体字可能对应多个繁体(OpenCC 用 | 分隔候选),取第一个
    const toFirst = to.split('|')[0]
    pairs.set(from, toFirst)
    if (from.length > maxLen) maxLen = from.length
  }
  return { pairs, maxLen }
}

const s2tChar = parseJs('STCharacters.js')
const s2tPhrase = parseJs('STPhrases.js')
const t2sChar = parseJs('TSCharacters.js')
const t2sPhrase = parseJs('TSPhrases.js')

function emitMap(name, pairs) {
  const lines = []
  for (const [k, v] of pairs) {
    lines.push(`  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
  }
  return `const ${name} = <String, String>{\n${lines.join('\n')}\n};\n`
}

const header = `// GENERATED FILE - DO NOT EDIT.
// Generated by tool/l10n/gen_han_data.mjs from OpenCC dictionary data
// (opencc-js, MIT licensed). Regenerate with: node tool/l10n/gen_han_data.mjs
// eslint-ignore
// ignore_for_file: constant_identifier_names

`
const body = [
  header,
  `/// 简体 -> 繁体 单字映射(OpenCC STCharacters)。`,
  emitMap('kSTCharacters', s2tChar.pairs),
  `/// 简体 -> 繁体 词组映射(OpenCC STPhrases)。`,
  emitMap('kSTPhrases', s2tPhrase.pairs),
  `/// 繁体 -> 简体 单字映射(OpenCC TSCharacters)。`,
  emitMap('kTSCharacters', t2sChar.pairs),
  `/// 繁体 -> 简体 词组映射(OpenCC TSPhrases)。`,
  emitMap('kTSPhrases', t2sPhrase.pairs),
  `/// 词组最长长度,用于最长匹配扫描。`,
  `const kSTMaxPhraseLen = ${s2tPhrase.maxLen};`,
  `const kTSMaxPhraseLen = ${t2sPhrase.maxLen};`,
].join('\n')

fs.writeFileSync(outPath, body, 'utf8')
console.log('written', outPath)
console.log(
  `s2t: chars=${s2tChar.pairs.size} phrases=${s2tPhrase.pairs.size} maxLen=${s2tPhrase.maxLen}`,
)
console.log(
  `t2s: chars=${t2sChar.pairs.size} phrases=${t2sPhrase.pairs.size} maxLen=${t2sPhrase.maxLen}`,
)
